nome = input('Qual é o seu nome? ')
idade = input('Qual é a sua idade? ')
peso = input('Qual é o seu peso? ')
print ('Seu nome é:', nome,)
print ('Você tem:', idade, 'anos')
print ('Seu peso é:', peso, 'Kg')
print ('')
