print('')
print('============= AULA 004 - DESAFIO 003 =============')
print('')
n1 = int(input('Digite o primeiro número: '))
n2 = int(input('Digite o segundo número: '))
n3 = int(input('Digite o terceiro número: '))
n4 = int(input('Digite o quarto número: '))
sn = n1+n2+n3+n4
# print('A soma dos valores é:', sn)
print('')
print('A soma dos valores é: {}'.format(sn))
print('')
# As duas linhas de comando a cima executam a mesma função.
print('========= FIM DA AULA 004 - DESAFIO 003 ==========')
print('')
