print(' ')
print('========= AULA 004 - DESAFIO 002 ==========')
print(' ')
nome = input('Qual é o seu nome? ')
print('Olá', nome, '!')
print('Seja bem vindo, prazer em te conhecer!')
print(' ')
dia = input('Que dia você nasceu? ')
mes = input('Mês de seu nascimento? ')
ano = input('Ano em que nasceu? ')
print('Você nasceu no dia', dia, 'de', mes, 'de', ano,'. Correto? ')
print('')
