print('')
print('======== EXERCICIO 004 ========')
#TIPOS PRIMITIVOS: int float bool str
v1 = input('Digite algo: ')
print('O tipo primitivo desse valor e:', type(v1))
print('Só tem espaços? ', v1.isspace())
print('É um número? ', v1.isnumeric())
print('É alfabetico? ', v1.isalpha())
print('É alfanumerico? ', v1.isalnum())
print('Está em maiusculas? ', v1.isupper())
print('Está em minusculas?', v1.islower())
print('Está capitalizada?', v1.istitle())
print('')
print('===== FIM DO EXERCICIO 004 =====')